# Generated by Django 5.1.2 on 2024-10-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("fitnessCoaching", "0001_initial"),
        ("fitnessCoaching", "0002_coaches_delete_item"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coaches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("body_type", models.CharField(max_length=100)),
                ("coach_age", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "coaches",
            },
        ),
    ]
