# Generated by Django 5.1.2 on 2024-10-24 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientsApp", "0001_squashed_0005_initial"),
        ("fitnessCoaching", "0001_squashed_0002_coaches_delete_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="coaches",
            name="clients",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coaches",
                to="clientsApp.clients",
            ),
        ),
    ]
