# Generated by Django 5.1.2 on 2024-10-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessCoaching", "0003_coaches_clients"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coaches",
            name="description",
        ),
        migrations.AddField(
            model_name="coaches",
            name="email",
            field=models.EmailField(
                default="example@gmail.com", max_length=254, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="coaches",
            name="coach_age",
            field=models.IntegerField(),
        ),
    ]
