# Generated by Django 5.1.2 on 2024-10-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitnessCoaching", "0004_remove_coaches_description_coaches_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coaches",
            name="email",
            field=models.EmailField(default="example@gmail.com", max_length=254),
        ),
    ]
