# Generated by Django 5.1.2 on 2024-10-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("clientsApp", "0001_initial"),
        ("clientsApp", "0002_alter_clients_table"),
        ("clientsApp", "0003_rename_coach_age_clients_client_age"),
        ("clientsApp", "0004_delete_clients"),
        ("clientsApp", "0005_initial"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("body_type", models.CharField(max_length=100)),
                ("client_age", models.CharField(max_length=2)),
            ],
            options={
                "db_table": "clients",
            },
        ),
    ]
