# Generated by Django 5.1.2 on 2024-10-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientsApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="clients",
            table="clients",
        ),
    ]
