# Generated by Django 5.1.2 on 2024-10-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientsApp", "0002_alter_clients_table"),
    ]

    operations = [
       
    ]
