# Generated by Django 5.1.2 on 2024-10-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientsApp", "0003_rename_coach_age_clients_client_age"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Clients",
        ),
    ]
