# Generated by Django 5.1.2 on 2024-10-24 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientsApp", "0006_remove_clients_description_clients_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clients",
            name="body_type",
        ),
    ]
